# Generated by Django 4.2.3 on 2023-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=True, verbose_name='مدير'),
            preserve_default=False,
        ),
    ]
