# Generated by Django 4.2.3 on 2023-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_how_i_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subtitle',
            field=models.TextField(max_length=250, verbose_name='نبذة عنك'),
        ),
    ]
