# Generated by Django 4.2.3 on 2023-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف'),
        ),
    ]
