# Generated by Django 4.2.3 on 2023-07-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_facebook_alter_profile_google_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_in',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الانضمام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Fmale')], default=1, max_length=50, verbose_name='النوع :'),
            preserve_default=False,
        ),
    ]
