# Generated by Django 4.2.3 on 2023-07-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_join_in_profile_type_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist_res',
            field=models.CharField(blank=True, choices=[('مطعم', 'مطعم'), ('بار', 'بار')], max_length=50, null=True, verbose_name='متخصص في'),
        ),
    ]
